### ISSUE TITLE
Using personal patch template

### ISSUE THREAD

**Issue by sdw0316** [kupl/npex#10]
Can I define and use a new path template rather than the default patch template?

**Comment by SeongjoonHong** [comment]
Yes. You can define your own patch template by implementing [PatchStrategy](../blob/master/synthesizer/src/main/java/npex/synthesizer/strategy/PatchStrategy.java) interface .
if a typical NPE patch with form of `if (nullcond) {...} else {...}` is enough, [AbstractStrategy](../blob/master/synthesizer/src/main/java/npex/synthesizer/strategy/PatchStrategy.java) may be a good starting point, where you only need to implement the `createNullBlockStmts` method that describes the null-block to be executed in the null-execution.
Once you define the patch strategy, construct a patch synthesizer object with the strategy.
